### ISSUE TITLE
Roadmap - MVP - Pre-Register & Make an Appointment

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-registration-api#1]
**Customer Story**: I am a person looking for food. I have been able to find a resource event I would like to attend through the FreshTrak.com website. I know want to enter my information to pre-register myself and secure an appointment. Having an appointment gives me added confidence that when I arrive I will be served, and my checkin process is 10x simpler than individuals who did not pre-register.

### Key Requirements:
- Integrate with an external-auth Provider - Facebook
- Make an account and login to FreshTrak with the external-auth capabilities
- Login and access previously created account
- Database - achieve ability to create, and control schema through code
- Outline minimum data requirements for each entity used in Pre-Register and Make An Appointment processes 
- CRUD functions for most of the entities
Account
Households- Document HOH information and write to FreshTrak Private Database & Document Family information and write to FreshTrak Private Database
Household Members - Document Counts of Family Members and write placeholder individuals to FreshTrak Private 
Household to Household Member Association - Only the C&R - Once someone is in a household do not update, or delete this association.
Appointments

Database
- Write an appointment record to the FreshTrak Private Database

### Validation: 
_Are there any examples of this strategy being tested?_
- [San Antonio Foodbank](https://abcnews.go.com/US/texas-food-bank-giving-100-pounds-food-families/story?id=70163511) - Had a drive through distribution and 6000+ people Pre-Registered.
![image](https://user-images.githubusercontent.com/11682225/80621830-dcb4bc80-8a15-11ea-8c66-f7cf8f8a3a41.png)
- [Greater Cleveland Food Bank](http://register.clevelandfoodbank.org/)

### PantryTrak & FreshTrak Scope and Scale

- 20+ Foodbanks use PantryTrak and can benefit from the implementation of FreshTrak in their service area
- 2000+ Agencies use PantryTrak and can receive pre-registrations and appointments from FreshTrak
- FreshTrak will be developed and tested within the Mid-Ohio Foodbank service area, and released to the rest of Ohio, and then the nation. All work done as part of this project can play a larger role in the nation's response to COVID-19.
- Map of Implementation in Ohio Footprint:
![National Map](https://user-images.githubusercontent.com/11682225/80624463-b42ec180-8a19-11ea-857d-04dbb674c161.png)

### MOF Systems Architecture

- We have an existing system called PantryTrak that functions like a Point-of-Sale for a food pantry (small neighborhood grocery-store like places that distribute food to customers).
- This project is to build the parts of FreshTrak that will receive customer information and appointments.
- **NOTE** - Information will be transferred from FreshTrak to PantryTrak, but this is not considered a strict technical dependency for FreshTrak to follow. Mid-Ohio Foodbank will write an ETL/Batch job to move the information from FreshTrak->PantryTrak. All Pre-Registrations and appointments will then flow into the established workflows inside of PantryTrak.

![image](https://user-images.githubusercontent.com/11682225/80622261-901db100-8a16-11ea-99e5-63274ad43a2c.png)

### FreshTrak Systems Architecture
![image](https://user-images.githubusercontent.com/11682225/80622163-6bc1d480-8a16-11ea-9c2d-28f7ecb66d86.png)

### Pseudo ERD Diagram
![image](https://user-images.githubusercontent.com/11682225/80622188-741a0f80-8a16-11ea-9aad-087fc479b5c8.png)

### Entity Definitions
![image](https://user-images.githubusercontent.com/11682225/80622647-15a16100-8a17-11ea-815a-e0aefc801760.png)

**Comment by csteele86** [comment]
You can find the current progress on the ERD here: https://drive.google.com/file/d/1gsb4DQcPoyqPHqs2WGdGMZG2-AZconzO/view?usp=sharing

**Comment by davidpickering** [comment]
![image](https://user-images.githubusercontent.com/11682225/81715887-bac02e80-9446-11ea-85cc-d7c36c7a2a10.png)

- household - question - This is partially dependent on the Front End. For example, if we got the front end fully developed for someone to input the age categories (children, adults, seniors), the system write "placeholder" household_member records, and then they detail the individual's information (Adult1 => Chris, Steele, etc...) then we don't need to hold onto that data outside of the Session. This concept is a little funky, so we can chat live about it if we need to.

![image](https://user-images.githubusercontent.com/11682225/81716373-4f2a9100-9447-11ea-8e05-4b2d86d47d12.png)

- household_members - ssn - "???" - That is correct! This field has long been deprecated in our system, and it was sloppy of me to include it in the screenshot. We do not need that in FreshTrak, and do not want it.

![image](https://user-images.githubusercontent.com/11682225/81716417-5b165300-9447-11ea-8aff-e03214613488.png)

- household_member_phone_numbers - has_special_permission - Yes, I think this should be a separate data structure as well. Someone can have N+1 phone numbers, so our data structure can reflect that even if the UI only has a way to write a single phone number for a while.

**Comment by csteele86** [comment]
@davidpickering thank you for the clarity!

**Comment by csteele86** [comment]
@davidpickering after tonight, here are some more questions I thought of:

1. Is it possible for each household member to have their own user account?
2. What is meant by "should hold email and/or phone" in the (member) contacts table description? Also, is that an inclusive list of all the various preferences?
3. I'm not completely following what you are saying about capturing the amount of certain types of people in a household. Front-end aside, what data are we trying to capture? Do we need to allow a registrant to bypass adding household members if they want by simply adding counts?
4. When reserving, is that always tied to the household or could it be tied to any household members?
5. Am I right in thinking that the "service_events" table is essentially data from the FreshTrak Pantry Finder API? If so, we wouldn't want to store all of the same data in this new database; just the event_slot_id (I believe) which would give us all of the event data. 
6. Similar to the question above, does all of the logic for reserving (status, who reserved, etc.) actually reside in the FreshTrak Pantry Database? Looking over the code, it "appears" so at first glance
7. Given the previous two questions, could you please elaborate more on the purpose and vision of the "service_status_log" table?

@andyschofield, would you have time to finish the ERD for the necessary tables to add Facebook auth?

**Comment by andyschofield** [comment]
@csteele86 yup, I'll try to have it finished by Friday standup.

**Comment by davidpickering** [comment]
> 1. Is it possible for each household member to have their own user account?

Yes, and I think this is a path we'll try to push users towards. Here is a typical path I think the data would get populated through:
1. Initial customer encounters FreshTrak, finds a distribution, then goes to make an appointment. 
2. They enter their family information (address + family size), and then generic placeholder family records are created. 
3. They have an optional opportunity to complete the information for each family member.
4. Long-Term - As the customer makes repeated visits to the site, they complete the information for each family member, including email and generate an "invitation to join the account".  The account is already linked to the household member.

> 2. What is meant by "should hold email and/or phone" in the (member) contacts table description? Also, is that an inclusive list of all the various preferences?

Sorry for any confusion of language. Basically, I'm just trying to say that for each household member we should be able to have N+1 phone numbers and N+1 emails. Whether or not we build UI to add multiple emails/phones is a different question. I think the more likely scenario is that people will have turnover in phone numbers and updating to a current number and inactivating another number will be a common occurrence.

> 3. I'm not completely following what you are saying about capturing the amount of certain types of people in a household. Front-end aside, what data are we trying to capture? Do we need to allow a registrant to bypass adding household members if they want by simply adding counts?

- Front-end aside we want to capture everyone's information that lives in the household. (e.g. Mom + Dad + 25-year old daughter + 15 year old son).
- Process wise - Yes, we want to allow a registrant to bypass adding household members if they want to. This could satisfy a generic privacy concern, and also a workflow issue - it takes a while to enter information for a 4-person household.
- Datawise - in our other system we get around the workflow issue by writing the placeholder family members (Mom + Adult 1 (Dad) + Adult 2 (25-year old daughter) + Child 1 (15 year old son))

> 4. When reserving, is that always tied to the household or could it be tied to any household members?

- It is primarily a property of the household - In the Food world services are logged to the household. 
- However, the workflow necessitates the need to record which individual scheduled the appointment + which individual is showing up for the appointment. When you show up at the site, they ask "what is your name" not "what is the name of the primary individuals in your household that established this appointment" - Haha, well
- So, we need the household_id, but if we write the household_member we can get to it just as easily while logging the data how we need it.
- Short answer: Let's write household_member to the appointment/reservation/service. If we need household_id downstream we know how to get to it.

> 5. Am I right in thinking that the "service_events" table is essentially data from the FreshTrak Pantry Finder API? If so, we wouldn't want to store all of the same data in this new database; just the event_slot_id (I believe) which would give us all of the event data.

- Yes, overall. Our process means that every "service_event" will come from from an event_date and be assigned to a specific event_slot, and strictly speaking we only need to write the event_slot_id. That is probably a nice refinement.
- The MVP only has event_date_id because we didn't want to build API Calls & UI to select the specific time (event_slot_id) beyond the date (event_date_id), full version can simplify/refine to the event_slot_id only.

> 6. Similar to the question above, does all of the logic for reserving (status, who reserved, etc.) actually reside in the FreshTrak Pantry Database? Looking over the code, it "appears" so at first glance

- We might need to discuss this further, because I don't think I exactly understand the question.
- If we are talking about properties of the Event Date (Date, Time, etc...) then correct, we can just retrieve those event_slot_id=>event_date as needed.
- If we are talking about other properties - e.g. which specific individuals is planning on picking up the service, or when the service was created, its current status (interested/reserved/cancelled by client/cancelled internal/served), etc... then those would be properties of the service_event and contained there.

> 7. Given the previous two questions, could you please elaborate more on the purpose and vision of the "service_status_log" table?
- The idea for the "service_status_log" table would mostly be about getting a temporal understanding of a customer's progress through the "sales funnel" of interested in an a distribution to making an appointment. We implemented this in our online ordering system and the information was quite interesting, and helped us understand how far people made it into the process and where they had issues.
- The practical usage of it is that if we want to update the status of the service_event, we want to log the change. This information is valuable to the agencies "When did this get changed to served", as well as if we need to reach out to individuals and cancel appointments - "status changed to cancelled.

@csteele86 Wow! Great questions! From what you asked I can tell you have really studied the information I shared and are critically thinking about it. I'm fine continuing the conversation here, but if we get really deep on something we can talk live if you'd like.

**Comment by andyschofield** [comment]
For documentation's sake, my plan is to use Devise to handle authentication on the various endpoints and to use OmniAuth to handle authentication to whatever external providers we want to use (Facebook, Google, etc). Devise might be a bit much for this project but it provides things like password reset flows which we would prefer to not implement ourselves.

I've updated the ERD @csteele86 shared earlier (https://drive.google.com/file/d/1gsb4DQcPoyqPHqs2WGdGMZG2-AZconzO/view?usp=sharing) with the information from the OmniAuth Auth Hash Schema (https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema).

Any comments are welcome

**Comment by davidpickering** [comment]
Thanks @andyschofield, I shared this updated in our stand up today. 

@csteele86 any outstanding questions for me in this ERD process? Any larger architecture conversations we need to have (e.g. service status logging)?

**Comment by csteele86** [comment]
@davidpickering, my apologies for the long delay here. I overlooked your response. In regards to the service status logging, would you be open to using temporal tables on the existing tables where we currently store the info you want to track the history on? One reason not to do this would be because we want to store more than what is already stored on the table. The following tables from the ERD would be marked as temporal:
- household_event_registrations
- household_event_registration_members

Also, for everyone's information, here are the updates I made to the ERD:
Updated the following tables:
- household
- household_event_registrations
- household_event_registration_members
- users_credentials

Added the following tables:
- event_statuses

**Comment by davidpickering** [comment]
We've mostly addressed these points, closing in favor of current projects details in Asana.
