### ISSUE TITLE
Household CRUD

### ISSUE THREAD

**Issue by chahn010** [midohiofoodbank/freshtrak-registration-api#14]
Add basic CRUD operations for the Household entity.

**Comment by chahn010** [comment]
@davidpickering @csteele86 @andyschofield @kazo0 @nvengal 

A few questions regarding households - business and technical. 

1. Should there be any restrictions when adding a household? Assuming we will collect address information at the time. Eg. No duplicate addresses per zip code? 

2. When updating a household, what fields should be considered for updating? I'm assuming household_name, household_number, address.

**Comment by davidpickering** [comment]
> Should there be any restrictions when adding a household? Assuming we will collect address information at the time. Eg. No duplicate addresses per zip code?
This is a kind of question we have long struggled with. If you put controls in front of processes you can unintentionally limit the usage of the feature. However, with no controls you get cruddy data (and not the good kind of CRUD). The general design guidance MOF would give is that we should do basic QAQC to help the user get it right, but don't want to block people from completing the process. 

Specifically, we do not want to prevent multiple households from registering at the same address. I'm happy to have a larger conversation around this if necessary.

> When updating a household, what fields should be considered for updating? I'm assuming household_name, household_number, address.

- name 👍 
- household_number ? - Is this the number of individuals in the household? How does this field relate to the data in the household_members table?
- address 👍  (absolutely)
