### ISSUE TITLE
Scaled Down MVP - Quick Path to Registration

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-registration-api#2]
Foodbank Story:

Context behind addition of scaled-back MVP: In the week of 4/26 & especially on 4/29 there were a few developments that 
The general feeling is that 
We are also feeling the need to prepare 

Basic Process Flow:

Pseudo-Data Model:
Model name: registrations
- unique key - int, autoinrement
- event_date_id
- date_submitted
- time_submitted
- first name - varchar - the HOH's first name
- middle name - varchar - the HOH's middle name
- last name - varchar - the HOH's last name
- suffix - varchar - the HOH'ssuffix (e.g. 2nd, 3rd, Jr. Sr., etc...)
- DOB - date - screen for reasonable values, apparently the oldest person is 112 years old, so date > 1908-01-01
- Gender (Male/Female/TransMale/TransFemale/Non-Binary/Prefer not to share)
- Phone Number
- Text permission
- Email
- email permission
(Family Information)
- Street Addr1
- Street Addr2
- Zip Code
- City
- State
- license_plate
(total number of household members)
- Seniors (60+)
- Adults (18-59)
- Children (0-17)
- hash_issued (AZ####)
- customer IP address

On wireframe, but not included:
- Head of Household

**Comment by nvengal** [comment]
Leaving IP address off for the moment, because I have to do a little bit of digging to understand where to pull it from in the lambda context. Commenting so that it doesn't get forgotten and we can come back to it at a later date.

**Comment by davidpickering** [comment]
This has been completed since before July!
