### ISSUE TITLE
Database Migration - add optional field to freshtrak_private.reservations for event_slot_id

### ISSUE THREAD

**Issue by maheshkurma** [midohiofoodbank/freshtrak-registration-api#21]
Database Migration - add optional field event_slot_id to reservations table.

**Comment by davidpickering** [comment]
Addressed by PR #25 
Not a lot of usage, but we have it in the database:
![image](https://user-images.githubusercontent.com/11682225/94639170-a96aa800-02a9-11eb-994f-44ce1991be55.png)
